# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "robertojrojas/win2k16-08041029"
  config.vm.box_version = "1.0.0"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "4024"
  end

  config.vm.define "c-dc1" do |dc1|
      dc1.vm.hostname = "dc1"
      dc1.vm.network "private_network", ip: "192.168.22.10"
  end

  config.vm.define "c-dc2" do |dc2|
      dc2.vm.hostname = "dc2"
      dc2.vm.network "private_network", ip: "192.168.22.11"
  end

  config.vm.define "c-ms1" do |ms1|
      ms1.vm.hostname = "ms1"
      ms1.vm.network "private_network", ip: "192.168.22.21"
  end
end